ShuffledScenario = """
    "[shuffle]"
    shuffle:
        "{FirstExtension}"
        "{SecondExtension}"
        "{ThirdExtension}"
        "{FourthExtension}"
        "{FifthExtension}"
        "{SixthExtension}"
        "{SeventhExtension}"
        "{EighthExtension}"
        "{NinthExtension}"
        "{TenthExtension}"
        "{EleventhExtension}"
        "{TwelfthExtension}"
    "{ThirteenthExtension}"
"""

# ShuffledScenario = """
# "первое // Да // Нет // 0 0 0 0 $ 0 0 0 0 // None" 
# "помощь ему // помощь // Нет // 0 0 0 0 $ 0 0 0 0 // None"
# "не должно быть // None // None // +20 +20 +20 +20 $ -20 -20 -20 -20 // None"
# """
